---
- hosts: [appserver]
  become: true
  gather_facts: False
  tasks:
    - name: install apache2, nginx & postgresql
      tags: apache, nginx, postgresql, postgres
      apt:
        name:
          - apache2
          - nginx
          - postgresql
          - postgresql-server
          - unzip
        state: latest
        update_cache: yes
    - name: default html page
      tags: apache,html,index
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.5.4/terraform_1.5.4_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root
---
- hosts: [webapp]
  become: true
  gather_facts: False
  tasks:
    - name: install apache, nginx & postgresql
      tags: httpd, nginx, postgres, postgresql
      yum:
        name:
          - httpd
          - nginx
          - postgresql
          - postgresql-server
        state: latest
        update_cache: yes
    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: httpd
        state: started
