---

- hosts: [appserver]
  become: true
  gather_facts: False
  tasks:

  - name: install apache2,htop and php package
    tags: apache, htop,php
    apt:
      name: 
        - apache2
        - libapache2-mod-php
        - htop
        - unzip
      state: latest
      update_cache: yes
  - name: default html page
    tags: apache,html,index
    copy:
      src: index.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.5.4/terraform_1.5.4_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
