---

- hosts: all
  become: true
  tasks:

  - name: install apache2,htop and php package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
        - htop
      state: latest
    when: ansible_distribution == "Ubuntu"
