---

- hosts: [appserver]
  become: true
  gather_facts: False
  tasks:

  - name: install apache2,htop and php package
    tags: apache, htop,php
    apt:
      name: 
        - apache2
        - libapache2-mod-php
        - htop
      state: latest
      update_cache: yes
