---
- hosts: [appserver]
  become: true
  gather_facts: False
  tasks:
    - name: install apache2 & postgresql
      tags: apache, postgresql
      apt:
        name:
          - apache2
          - postgresql
          - unzip
        state: latest
        update_cache: yes
    - name: default html page
      tags: apache,html,index
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.5.4/terraform_1.5.4_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root

- hosts: [webapp]
  become: true
  gather_facts: False
  tasks:
    - name: install apache, & postgresql
      tags: httpd, postgres, postgresql
      ansible.builtin.dnf:
        name:
          - httpd
          - postgresql
        state: latest
        update_cache: yes
    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: httpd
        state: started
    - name: Ensure that postgresql is started
      ansible.builtin.service:
        name: postgresql
        state: started
    - name: default html page
      tags: apache,html,index
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
