---

- hosts: [web-server]
  become: true
  tasks:

  - name: install apache2,htop and php package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
        - htop
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
