---
- hosts: all
  become: true
  tasks:
    - name: Remove the Apache, postgresql package
      apt:
        name:
          - apache2
          - postgresql
        state: absent
      #when: ansible_distribution == "Ubuntu"
    - name: Remove the Apache, postgresql package
      dnf:
        name:
          - httpd
          - postgresql
          - postgresql-server
        state: absent
      #when: ansible_distribution == "Fedora"
